# Generated by Django 4.0.5 on 2023-05-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='id',
        ),
        migrations.AlterField(
            model_name='userform',
            name='Biometricid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
